name: Deploy Preview Deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: lorisleiva/laravel-docker
    steps:
      - name: "Deploy Preview"
        run: |
          composer global require ryangjchandler/forge-previewer && \
          ./root/.composer/vendor/bin/forge-previewer
