name: Deploy Preview Deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker
      options: "--entrypoint /bin/bash"
    steps:
      - name: "Deploy Preview"
        run: |
          composer config --global --list
