name: Deploy Preview Deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: lorisleiva/laravel-docker
    steps:
      - run: echo "🎉 The job was automatically triggered"
