name: Deploy Preview Deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: lorisleiva/laravel-docker
    steps:
      - name: "Deploy Preview"
        run: |
          composer config --global --list
          ls -al ~/.composer/vendor
          ls -al ~/.composer/vendor/bin
