name: Deploy Preview Deployment

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker
    steps:
      - name: "Deploy Preview"
        run: |
          docker ps -a
