name: Preview

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout branch
      #   uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Forge Previewer
        run: composer global require ryangjchandler/forge-previewer

      - name: Deploy preview environment
        run: forge-previewer deploy --token=${{ secrets.FORGE_TOKEN }} --server=${{ secrets.FORGE_PREVIEW_SERVER }} --repo=${{ github.repository }} --branch=${{ github.head_ref }} --domain=${{ secrets.FORGE_PREVIEW_DOMAIN }}
